version: 3

dotenv: [ ".env" ]

env:
  MULTI_MEGA_SYNC_HOME:
    sh: "[ -f .env ] && . .env ; echo ${MULTI_MEGA_SYNC_HOME:-/multi-mega-sync}"

tasks:
  setup:
    silent: true
    cmds:
      - mkdir -p "${MULTI_MEGA_SYNC_HOME}"