version: 3

dotenv: [ ".env" ]

env:
  MULTI_MEGA_SYNC_HOME:
    sh: "[ -f .env ] && . .env ; echo ${MULTI_MEGA_SYNC_HOME:-/multi-mega-sync}"

tasks:
  requirements:
    silent: true
    cmds:
      - sudo apt-get install -y jq megasync
  setup:
    silent: true
    cmds:
      - mkdir -p "${MULTI_MEGA_SYNC_HOME}"
  start:
    silent: true
    cmds:
      - |
        jq -r '.instances[] | "\(.folder)"' config.json | while read folder; do
          HOME="${MULTI_MEGA_SYNC_HOME}/$folder"
          echo "Launching MegaSync for $HOME"
          megasync 2 > /dev/null &
          sleep 2
        done
  stop:
    silent: true
    cmds:
      - killall megasync